/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio4POO;

public class App {
    

    public static void main(String[] args) {
Elevador e1 = new Elevador();

e1.setCapacidadeElevador(5);
e1.inicializar();
e1.entrar();
e1.subir();
e1.subir();
e1.entrar();
e1.entrar();
e1.entrar();
e1.entrar();
e1.subir();
e1.subir();
e1.subir();
e1.subir();
e1.subir();
e1.sair();
e1.descer();
e1.subir();
e1.descer();


//Status
e1.status();


    }
}
