/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Exercicios;

import java.util.Scanner; //baixa biblioteca de leitura

public class App {


    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in); //cria o scanner leitor
        System.out.println("Digite um valor: "); //frase antes do usuário digitar valor

            int numero = leitor.nextInt(); //declara parâmetro para ser próximo int lido

            if(numero>=100 && numero<=200){
                System.out.println("O numero esta entre 100 e 200.");

            }

            else {
                System.out.println("Digite outro numero valido.");
            }
    }
}


