/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Condicionais;

public class App {

    public static void main(String[] args) {
//Estrutura IF
           int media = 7;

           if(media >= 7){
            System.out.println("Aprovado");

           }

           else {
           System.out.println("Reprovado");
           }


//Estrutura Switch
int codigoProduto = 2;

            switch(codigoProduto){
            case 1:
                System.out.println("Sabonete");
            break;

            case 2:
                System.out.println("Shampoo");
            break;
            case 3:
                System.out.println("Condicionador");
            break;
            default:
                System.out.println("Não tem esse produto");
            break;

            }
    }
}



