/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio1POO;

public class App {
  

    public static void main(String[] args) {
        Pessoa p1 = new Pessoa();

p1.setNome("Sabrina");
p1.setAltura(1.70f);
p1.setAnoNascimento(2004);
p1.status();
p1.calcularIdade();

    }
}


