/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercicio6;
import java.util.Scanner;
public class App {
    public static void main(String[] args) {
Scanner leitor = new Scanner(System.in);

float A;
float B;
float C = 0;

System.out.println("Digite um valor para A: ");
A = leitor.nextFloat();
System.out.println("Digite um valor para B: ");
B = leitor.nextFloat();

C = A;
A = B;

System.out.println("Valor de A: " + B + " e valor de B: " + C );


    }
}
